import Config

# Configure your database
config :elixir_phx, ElixirPhx.Repo,
  username: System.get_env("DB_USERNAME", "postgres"),
  password: System.get_env("DB_PASSWORD", "postgres"),
  hostname: System.get_env("DB_HOST", "localhost"),
  database: System.get_env("DB_NAME", "elixir_phx_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :elixir_phx, ElixirPhxWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "0oblGmxQ3trMAU0tlx/yZWqpmnjO8D8lGSoGMkDutoBgw5FIYihWJduylSU1bP6N",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :elixir_phx, dev_routes: true

# JSON logging configuration (logger_json v7.x - using :logger_json formatter)
config :logger,
  level: :debug,
  backends: [:console, {LoggerFileBackend, :file_log}]

# Console logging with JSON format
config :logger, :console,
  formatter: :logger_json,
  metadata: :all

# File logging with JSON format for OpenTelemetry collector scraping
config :logger, :file_log,
  path: "log/elixir_phx.log",
  formatter: :logger_json,
  metadata: :all,
  rotate: %{max_bytes: 10_485_760, keep: 5}

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix, :logger, false

# OpenTelemetry development configuration
config :opentelemetry_exporter,
  otlp_protocol: :http_protobuf,
  otlp_endpoint: System.get_env("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4318")

config :opentelemetry,
  resource: [
    service: [
      version: "0.1.0",
      namespace: "development"
    ]
  ],
  span_processor: :batch,
  traces_exporter: :otlp,
  logs_exporter: :otlp
